import { StyleSheet } from 'react-native';

const ScorePanelStyles = StyleSheet.create({
  card: {
    width: '100%',
    maxWidth: 420,
    minWidth: 180,
    padding: 20,
    borderRadius: 16,
    backgroundColor: '#bdbdbd',
    borderWidth: 4,
    borderColor: '#007AFF',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 20,
  },
  panelContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 24,
    width: '100%',
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  playerName: {
    width: '100%',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#e0dede',
    fontWeight: 'bold',
    fontSize: 17,
    textAlign: 'center',
    marginBottom: 10,
  },
  scoreBox: {
    width: '100%',
    backgroundColor: '#4dd0e1',
    borderRadius: 8,
    paddingVertical: 10,
    marginBottom: 14,
    alignItems: 'center',
  },
  scoreText: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#000',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    flexWrap: 'wrap',
    gap: 8,
  },
  button: {
    flex: 1,
    minWidth: 100,
    marginHorizontal: 4,
    backgroundColor: '#f5e9e0',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 8,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
});

export default ScorePanelStyles;
